### PR TITLE
improve icon colors

### PR DESCRIPTION
**Pull request by balping**
Plain blue over the red was just painful to look at. After long experimentation I picked two new colors using an online color palette generator: https://paletton.com/#uid=5000u0kyHrZpCUyu0JXwWhfxr63

Feel free to choose another combination if you'd like to, just please don't leave the arrow at 0000FF.

Also, I optimised the png icons using lossless compression by Trimage.

a_256x256 &rarr; 256x256

### CODE REVIEW

**Comment by JaGoLi** [comment]
Thank you for you input! I'm by no means a graphical designer, but I just needed a damn icon for my app. Personally, I do like your choice of red a lot better, however I maybe would like to see another prototype if you can with a color that offers more contrast for the arrow. Maybe some shade of blue?

**Comment by balping** [comment]
> I'm by no means a graphical designer

Nor am I :smile: 

I tried some blue-ish colors, but couldn't find one that looked good to me. Maybe someone more experienced could do it.

**Comment by JaGoLi** [comment]
Can you try to find me a shade of light blue that I pleasing on the eyes, like pastel color?

**Comment by JaGoLi** [comment]
Also, please submit a pull request for beta branch, as a change like this will affect the packages created.

**Comment by JaGoLi** [comment]
A submission for a new icon has been approved.

**Pull request closed without merging**
